apiVersion: v1
kind: Pod
metadata:
  name: ${id}
  labels:
    run: ${id}
spec:
  containers:
  - name: ${id}
    image: ${image}
    ports:
    - containerPort: 22224
    - containerPort: 5901
    securityContext:
      privileged: true
    volumeMounts:
    - name: xsocket
      mountPath: /tmp/.X11-unix/X0
      readOnly: false
    - name: workdir
      mountPath: /Projects/hobotrl/playground/initialD/test/experiment
  volumes:
  - name: xsocket
    hostPath:
      path: /var/xserver-daemon/X0
      type: File
  - name: workdir
    hostPath:
      path: /mnt/glusterfs/lisen.mu
  nodeSelector:
    xserver-daemon: "yes"
