apiVersion: v1
kind: Pod
metadata:
  name: ${id}
  labels:
    run: ${id}
spec:
  containers:
  - name: ${id}
    image: ${image}
    ports:
    - containerPort: 22224
    - containerPort: 5901
    securityContext:
      privileged: true
    volumeMounts:
    - name: xsocket
      mountPath: /Projects/.X11-unix
      readOnly: false
  volumes:
  - name: xsocket
    hostPath:
      path: /var/xserver-daemon
  nodeSelector:
    xserver-daemon: "yes"