apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rl-validation
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.31.40.197
    path: "/mnt/a/lewis/inference"
