apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rl-validation-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: nfs-rl-validation
