# yaml file for deploying env-api-server
apiVersion: v1
kind: Service
metadata:
  name: env-api-server
  labels:
    run: env-api-server
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: websocket
  selector:
    run: env-api-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: env-api-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: env-api-server
    spec:
      containers:
      - name: env-api-server
        image: docker.hobot.cc/carsim/api:0.1.1
        ports:
        - containerPort: 8080
