apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: DaemonSet
metadata:
  name: xserver-daemon
  namespace: default
  labels:
    name: xserver-daemon
spec:
  selector:
    matchLabels:
      name: xserver-daemon
  template:
    metadata:
      labels:
        name: xserver-daemon
    spec:
      containers:
      - name: xserver-daemon
        image: docker.hobot.cc/carsim/opengl-3dx:latest
        securityContext:
          privileged: true
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - name: xsocket
          mountPath: /tmp/.X11-unix
          readOnly: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: xsocket
        hostPath:
          path: /var/xserver-daemon
          type: DirectoryOrCreate
      nodeSelector:
        xserver-daemon: "yes"